-- Insert default admin account
-- Email: kuutech0101@gmail.com
-- Password: kuutech153624
-- Note: Run backend/fix_admin_password.js to generate the correct hash

USE yango_db;

-- First delete any existing admin accounts
DELETE FROM admins WHERE email = 'kuutech0101@gmail.com' OR email = 'admin@yango.com';

-- Insert admin account
-- The hash below needs to be generated by running: node backend/fix_admin_password.js
INSERT INTO admins (name, email, password, role) VALUES 
('KuuTech Admin', 'kuutech0101@gmail.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'super_admin');

-- Verify the admin was created
SELECT * FROM admins;
